languageCode = 'en-us'
title = 'micro.pinapelz.moe'
theme = "MinIndie"
baseURL = "https://micro.pinapelz.moe"
publishDir = "../micro.pinapelz.moe"

[params]
subtitle = "check it out. I'm in the house like carpet"
dateFmt = "Monday, January 2, 2006"
# tagPostOlderThanXDays = 555 # To display a message if the post is older than this number of days.
# xslpath = "/rss.xsl" # If you want to theme your RSS feed. Optional.

[params.author]
    name = "Pinapelz"
    email = "yukais@pinapelz.com"
    avatar = "https://files.catbox.moe/5r1pue.jpg"
    banner = "https://files.pinapelz.com/pso2ngs-2232-collab.png"
    bio = '''yo! and he's more than a cover he's a quilt<br/>
    General arcade rhythm game enjoyer (SDVX, IIDX, CHUNITHM)<br/>
    Mostly play MMOs (FFXIV, OSRS), JRPGs, and VNs (anything with a good story)<br/>
    I Watch only slice of life (and Bandori)<br/>
    Arch Linux + Hyprland user (btw)<br/>
    Hi from the <a href="https://indieweb.org/">indieweb</a>, if you are seeing me bridged elsewhere!'''
[params.indieweb]
    authorizationEndpoint = "https://indieauth.com/auth"
    tokenEndpoint = "https://tokens.indieauth.com/token"
    webmentionEndpoint = "https://webmention.io/micro.pinapelz.moe/webmention"
    relmepgp = "https://pinapelz.com/Yukai_Shan.asc"
    [[params.indieweb.relme]]
        url = "https://github.com/pinapelz"
    [[params.indieweb.relme]]
        url = "mailto:yukais@pinapelz.com"
    [[params.indieweb.relme]]
         url = "https://sakurajima.social/@pinapelz"
    [[params.indieweb.relme]]
        url = "https://bsky.app/profile/pinapelz.moe"


# Menus:
[menu]
[[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

## Footer
[[menu.footer]]
    name = "Github"
    url = "https://github.com/pinapelz"
    weight = 1

[[menu.footer]]
    name = "pinapelz.moe"
    url = "https://pinapelz.moe"
    weight = 1
